/* 「어디서 무슨 말? 말 경매」 카드 데이터 (지시서 원본 그대로. 낱말·꼬리표를 다듬지 말 것)
   board.html · team.html 이 <script src="sets/mal.js"> 로 읽는다(모듈이 아니라 일반 스크립트 → file:// 로 열어도 동작).
   REGION_MISMATCH 는 기본값. 칠판 [⚙ 수정 > 진행]에서 바꾸면 그 컴퓨터에 저장된 값이 우선한다. */
const SET_MAL = {
  name: "어디서 무슨 말? 말 경매",
  types: ["자리","말","듣는 사람","말투"],
  criteria: ["듣는 사람이 그 말을 알아들을까? (지역)","높임이 맞나? (웃어른·모르는 사람에게 반말은 안 된다)","그 자리의 분위기에 맞는 말인가? (격식 있는 자리 / 편한 자리)","방언은 틀린 말이 아니다. \"어울리나\"만 따진다."],
  place: [ // mood: 격식 | 편함
    {id:"p1", text:"부산 할머니 댁 추석 저녁상", mood:"편함"},
    {id:"p2", text:"제주 민박집에 손님이 들어온다", mood:"편함"},
    {id:"p3", text:"전국에 나가는 라디오 뉴스", mood:"격식"},
    {id:"p4", text:"교장실에서 아침 인사", mood:"격식"},
    {id:"p5", text:"전학 온 첫날 교실", mood:"격식"},
    {id:"p6", text:"급식실 배식 줄", mood:"편함"},
    {id:"p7", text:"충청도 시골 장터에서 물건 사기", mood:"편함"},
    {id:"p8", text:"축구 경기장 응원석", mood:"편함"},
    {id:"p9", text:"병원 진료실", mood:"격식"},
    {id:"p10", text:"이야기 「멋져 부러, 세발자전거!」 속 마을", mood:"편함"},
    {id:"p11", text:"친구 생일 파티", mood:"편함"},
    {id:"p12", text:"처음 가는 친구 집, 현관에서", mood:"격식"},
    {id:"p13", text:"온라인 게임 채팅", mood:"편함"},
    {id:"p14", text:"강원도 할아버지 생신 잔치", mood:"편함"},
    {id:"p15", text:"외국인 관광객에게 길 안내", mood:"격식"},
  ],
  word: [ // region: 제주|경상|충청|강원|전라|표준 · honor: 반말|해요|격식|무관
    {id:"w1", text:"혼저 옵서예", region:"제주", honor:"해요", meaning:"어서 오세요"},
    {id:"w2", text:"어서 오이소", region:"경상", honor:"해요", meaning:"어서 오세요"},
    {id:"w3", text:"어서 오슈", region:"충청", honor:"해요", meaning:"어서 오세요"},
    {id:"w4", text:"어서 오시우야", region:"강원", honor:"해요", meaning:"어서 오세요"},
    {id:"w5", text:"어서 오세요", region:"표준", honor:"해요", meaning:""},
    {id:"w6", text:"안녕하십니까", region:"표준", honor:"격식", meaning:""},
    {id:"w7", text:"밥 뭇나?", region:"경상", honor:"반말", meaning:"밥 먹었니?"},
    {id:"w8", text:"밥 먹었어?", region:"표준", honor:"반말", meaning:""},
    {id:"w9", text:"식사하셨어요?", region:"표준", honor:"해요", meaning:""},
    {id:"w10", text:"짐치 좀 주이소", region:"경상", honor:"해요", meaning:"김치 좀 주세요"},
    {id:"w11", text:"김치 좀 주세요", region:"표준", honor:"해요", meaning:""},
    {id:"w12", text:"고냉이", region:"제주", honor:"무관", meaning:"고양이"},
    {id:"w13", text:"고양이", region:"표준", honor:"무관", meaning:""},
    {id:"w14", text:"멋져 부러!", region:"전라", honor:"반말", meaning:"정말 멋져!"},
    {id:"w15", text:"정말 멋지다!", region:"표준", honor:"반말", meaning:""},
  ],
  listener: [ // region: 위와 같음 + 전국|외국 · relation: 웃어른|친구|모르는 사람|전국
    {id:"l1", text:"부산 할머니", region:"경상", relation:"웃어른"},
    {id:"l2", text:"서울에서 온 손님 가족", region:"표준", relation:"모르는 사람"},
    {id:"l3", text:"전국 청취자", region:"전국", relation:"전국"},
    {id:"l4", text:"교장 선생님", region:"표준", relation:"웃어른"},
    {id:"l5", text:"처음 보는 반 친구들", region:"표준", relation:"친구"},
    {id:"l6", text:"급식 조리사 선생님", region:"표준", relation:"웃어른"},
    {id:"l7", text:"충청도 장터 아주머니", region:"충청", relation:"웃어른"},
    {id:"l8", text:"옆자리에서 같이 응원하는 아저씨", region:"표준", relation:"모르는 사람"},
    {id:"l9", text:"의사 선생님", region:"표준", relation:"웃어른"},
    {id:"l10", text:"이야기 속 마을 친구", region:"전라", relation:"친구"},
    {id:"l11", text:"단짝 친구", region:"표준", relation:"친구"},
    {id:"l12", text:"친구 어머니", region:"표준", relation:"웃어른"},
    {id:"l13", text:"같이 게임하는 친구", region:"표준", relation:"친구"},
    {id:"l14", text:"강원도 할아버지", region:"강원", relation:"웃어른"},
    {id:"l15", text:"한국어를 조금 아는 외국인", region:"외국", relation:"모르는 사람"},
  ],
  tone: [ // ok: 비어 있으면 항상 어울림. moods/relations 둘 다 있으면 둘 다 만족해야 함
    {id:"t1", text:"웃으며", ok:{}},
    {id:"t2", text:"큰 소리로", ok:{moods:["편함"]}},
    {id:"t3", text:"고개 숙이며", ok:{relations:["웃어른","모르는 사람"]}},
    {id:"t4", text:"조심스럽게 작은 소리로", ok:{moods:["격식"]}},
    {id:"t5", text:"손 흔들며", ok:{relations:["친구"]}},
    {id:"t6", text:"툭 던지듯 빠르게", ok:{moods:["편함"], relations:["친구"]}},
  ],
};
const REGION_MISMATCH = "X"; // "X" 또는 "△". 담임이 바꿀 수 있게 설정 화면에 노출
